Add support to device registration
astarte-platform/astarte-device-sdk-java pull request #23
Opened 2021-06-09 10:09 UTC by harlem88

- AstartePairingService: add class responsible for communicating with Astarte Pairing API
- AstartePairingHandler: move pairing code to AstartePairingService class

2021-06-10 11:01 UTC, bettio requested changes
In addition to my previous comments:

- This change is relevant for our users, and the new `registerDevice` method should be documented in our changelog.
-  Commit messages should be changed as suggested in #22 PR.

I'm not sure if it would be better to merge this change into release-1.0, for feature parity reason, or rather merge it into master. However I think that there are good points about merging it into release-1.0.

2021-06-10 11:04 UTC, bettio commented
About the PR description, I think we should focus on "What" rather than on "How.
As I know the main focus of this PR is adding an API for device registration using Astarte Pairing API REST API, but the PR message doesn't makes this clear.

2021-06-10 14:34 UTC, harlem88 commented on DeviceSDK/src/main/java/org/astarteplatform/devicesdk/AstartePairingService.java
> +public final class AstartePairingService {
I think AstartePairingService is the right name, because the operation does not conceptually belong to AsterteDevice object.

2021-06-11 13:09 UTC, bettio requested changes

2021-06-11 13:09 UTC, bettio commented on CHANGELOG.md
> +## [Unreleased]
This should be `## [1.0.0] - Unreleased`

2021-06-11 13:09 UTC, bettio commented on DeviceSDK/src/main/java/org/astarteplatform/devicesdk/AstartePairingService.java
> +          "Null Pointer exception - probably got a " + "wrong payload?", e);
Concat here can be replaced with the concatenated string.

2021-06-11 13:12 UTC, bettio commented
We are still not clearly telling our users what this change is about. E.g.
"Add support to device registration. It is possible to blah blah".

When we write something like "AstartePairingHandler: move the pairing request to AstartePairingService class" we are stating something that is clear when opening the diff, however it is not clear at all why we are doing this.

2021-06-11 16:43 UTC, rbino approved these changes

2021-06-14 13:26 UTC, bettio approved these changes

2021-06-14 16:18 UTC, merged