Fix ClassCastException: deserialize method in AstarteGenericPropertyStorage class
astarte-platform/astarte-device-sdk-java pull request #24
Opened 2021-06-09 15:34 UTC by harlem88

This change fixes the `ClassCastException: cannot be cast to org.bson.BsonValue` in AstarteGenericPropertyStorage deserialize method.

2021-06-10 09:58 UTC, bettio requested changes
This looks like a bugfix, I think we should rebase it on top of release-1.0 and merge it into that branch.
Please, make sure to avoid including any master commit into this branch by properly rebasing it.

2021-06-10 10:00 UTC, rbino commented
Actually I'd say this should point to the 0.11 branch since the code exists there too

2021-06-11 13:01 UTC, bettio approved these changes

2021-06-11 13:01 UTC, bettio requested changes
changelog needs a couple of changes.

2021-06-11 16:43 UTC, rbino approved these changes

2021-06-14 13:22 UTC, bettio approved these changes

2021-06-14 13:22 UTC, merged