Add support to array-type values
astarte-platform/astarte-device-sdk-java pull request #44
Opened 2021-09-22 13:00 UTC by FrancescoVaiani

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2021-09-22 15:30 UTC, harlem88 requested changes

2021-09-22 15:30 UTC, harlem88 commented on DeviceSDK/src/main/java/org/astarteplatform/devicesdk/protocol/AstarteInterfaceMapping.java
> +    return otherType == getType() || otherType == primitiveArrayType;
Don't use accessor methods for local fields. 
`return otherType == this.type || otherType == this.primitiveArrayType;`

2021-09-23 09:31 UTC, harlem88 approved these changes

2021-09-23 13:20 UTC, harlem88 approved these changes

2021-09-23 15:44 UTC, bettio approved these changes

2021-09-23 15:47 UTC, merged