Android: Fix generation Astarte Device ID.
astarte-platform/astarte-device-sdk-java pull request #45
Opened 2021-09-24 07:28 UTC by harlem88

- Android api level 23 doesn't support Base64.getEncodeUrl function.
- Move unit test files to the right folder.

2021-09-24 08:21 UTC, FrancescoVaiani approved these changes

2021-09-27 15:17 UTC, bettio requested changes

2021-09-27 15:29 UTC, rbino requested changes

2021-09-27 15:29 UTC, rbino commented on DeviceSDKGeneric/src/main/java/org/astarteplatform/devicesdk/AstarteDeviceIdUtils.java
> -
Removed extra line here, restore it to reduce commit whitespace noise

2021-09-28 14:22 UTC, merged