Add dynamic interface load
astarte-platform/astarte-device-sdk-java pull request #50
Opened 2022-01-12 14:55 UTC by FrancescoVaiani

Add the capability to load and unload interfaces dynamically in device's introspection calling the `addInterface` and `removeInterface` functions of the `AstarteDevice` class. The `AstartePairableDevice` class extends said functions to add the capability to send the altered introspection to the server if the device is connected. The function `loadInterface` in the `InterfaceProvider` can be implemented to help load interfaces by name and instanciate them to `JSONObject` similarly to the `loadAllInterfaces` does for a batch of interfaces as shown in the `ExampleInterfaceProvider` example implementation.

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-01-25 16:22 UTC, harlem88 approved these changes

2022-10-17 15:18 UTC, rbino requested changes
Missing CHANGELOG entry

2022-12-05 10:54 UTC, rbino requested changes

2022-12-05 10:54 UTC, rbino commented on DeviceSDK/src/main/java/org/astarteplatform/devicesdk/AstarteDevice.java
> +  public void addInterface(JSONObject astarteInterfaceObject)
What happens if you call this with an interface with the same name and major but a different minor?
The expected behaviour I'm thinking about is:
- Same minor: exception is raised (as it is right now)
- New minor < old minor: exceptions is raised (can't downgrade an interface at runtime)
- New minor > old minor: the new interface replaces the old one

Please confirm if this is the actual behaviour

2022-12-05 13:17 UTC, harlem88 approved these changes

2022-12-06 10:59 UTC, harlem88 approved these changes

2022-12-06 16:10 UTC, bettio approved these changes

2022-12-06 16:10 UTC, merged