Add Document publication workflow
astarte-platform/astarte-device-sdk-java pull request #55
Opened 2022-03-03 15:51 UTC by FrancescoVaiani

- Add a Gradle task to aggregate all the various projects javadocs in a single documentation. The Gradle task was adapted from Netflix Nebula `gradle-aggregated-javadocs` to add support to Android projects.
- Add a documentation workflow for GitHub actions to automatize the publication of javadocs.

Please note that the `DOCS_DEPLOY_KEY` shh key must be set up in the project secrets in order to allow the workflow to commit in the documentation repository.

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-03-04 09:00 UTC, harlem88 requested changes

2022-03-04 09:00 UTC, harlem88 commented on scripts/aggregate-javadoc-plugin.gradle
> +apply plugin: AggregateJavadocPlugin
No newline at end of file

2022-03-04 15:50 UTC, harlem88 requested changes

2022-03-04 15:50 UTC, harlem88 commented on .github/workflows/doc-workflow.yaml
> +name: Build flow
Change  name in something like that `Docs generation for Github Pages`

2022-03-04 16:13 UTC, harlem88 approved these changes

2022-03-10 11:52 UTC, bettio approved these changes

2022-03-10 11:52 UTC, merged