Handle the sessionPresent flag from the broker
astarte-platform/astarte-device-sdk-java pull request #66
Opened 2022-10-07 10:48 UTC by FrancescoVaiani

It looked like the SDK sent the introspection and all properties every time the device connected even if it was a temporary disconnection. The right behavior should be that those data should be sent only on the first connection or if [the session was cleaned by the broker because considered invalid](https://docs.astarte-platform.org/latest/080-mqtt-v1-protocol.html#session-present).
That anomaly was generated by the MQTT Client library cleaned the session by default for each connection.
This commit deactivates that default behavior.

Close #65 

Signed-off-by: Francesco Vaiani <francesco.vaiani@secomind.com>

2022-10-17 13:17 UTC, harlem88 approved these changes

2022-12-05 10:50 UTC, rbino approved these changes

2022-12-05 10:50 UTC, rbino requested changes
Missing CHANGELOG entry

2022-12-05 13:18 UTC, harlem88 approved these changes

2022-12-12 16:59 UTC, merged