Expose path from aggregate datastream event
astarte-platform/astarte-device-sdk-java pull request #83
Opened 2023-07-18 12:53 UTC by nedimtokic

Expose full interface path from aggregate datastream event to a caller. 
If the object is sent on endpoint `/config/1/param/2` using interface mapping:
``` 
"mappings":
    {
       "endpoint": "/config/%{config_id}/param/%{param_id}/duration",
       "type": "integer",
     }
```
, then the caller can receive the same path using the `getPath()` property of 'AstarteAggregateDatastreamEvent' as shown in the examples.
Closes #82

2023-07-20 14:51 UTC, harlem88 commented
Add entry to the Changelog: 
### Added
- Expose an interface path from Astarte aggregate datastream event.

2023-07-28 07:47 UTC, harlem88 requested changes

2023-07-28 07:47 UTC, harlem88 commented on CHANGELOG.md
> +- Expose an interface path from Astarte aggregate datastream event.
Move this entry to `Unreleasd` tag
```
## [Unreleased]
### Added
- Expose an interface path from Astarte aggregate datastream event.
```

2023-07-28 08:13 UTC, nedimtokic commented on CHANGELOG.md
> +- Expose an interface path from Astarte aggregate datastream event.
Moved to `Unreleased `section.

2023-07-28 08:40 UTC, harlem88 approved these changes

2023-08-08 14:09 UTC, lucaato approved these changes

2023-08-10 13:00 UTC, merged